// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mimc.proto

package mimc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//************MessageFilter***********
type ErrorCode int32

const (
	ErrorCode_OK             ErrorCode = 0
	ErrorCode_INTERNAL_ERROR ErrorCode = 1
)

var ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
}

var ErrorCode_value = map[string]int32{
	"OK":             0,
	"INTERNAL_ERROR": 1,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{0}
}

type MIMC_MSG_TYPE int32

const (
	MIMC_MSG_TYPE_P2P_MESSAGE      MIMC_MSG_TYPE = 1
	MIMC_MSG_TYPE_P2T_MESSAGE      MIMC_MSG_TYPE = 2
	MIMC_MSG_TYPE_SEQUENCE_ACK     MIMC_MSG_TYPE = 3
	MIMC_MSG_TYPE_PACKET_ACK       MIMC_MSG_TYPE = 4
	MIMC_MSG_TYPE_PULL             MIMC_MSG_TYPE = 5
	MIMC_MSG_TYPE_COMPOUND         MIMC_MSG_TYPE = 6
	MIMC_MSG_TYPE_RTS_SIGNAL       MIMC_MSG_TYPE = 7
	MIMC_MSG_TYPE_UC_PACKET        MIMC_MSG_TYPE = 8
	MIMC_MSG_TYPE_P2P_PUSH_MESSAGE MIMC_MSG_TYPE = 9
	MIMC_MSG_TYPE_P2T_PUSH_MESSAGE MIMC_MSG_TYPE = 10
)

var MIMC_MSG_TYPE_name = map[int32]string{
	1:  "P2P_MESSAGE",
	2:  "P2T_MESSAGE",
	3:  "SEQUENCE_ACK",
	4:  "PACKET_ACK",
	5:  "PULL",
	6:  "COMPOUND",
	7:  "RTS_SIGNAL",
	8:  "UC_PACKET",
	9:  "P2P_PUSH_MESSAGE",
	10: "P2T_PUSH_MESSAGE",
}

var MIMC_MSG_TYPE_value = map[string]int32{
	"P2P_MESSAGE":      1,
	"P2T_MESSAGE":      2,
	"SEQUENCE_ACK":     3,
	"PACKET_ACK":       4,
	"PULL":             5,
	"COMPOUND":         6,
	"RTS_SIGNAL":       7,
	"UC_PACKET":        8,
	"P2P_PUSH_MESSAGE": 9,
	"P2T_PUSH_MESSAGE": 10,
}

func (x MIMC_MSG_TYPE) Enum() *MIMC_MSG_TYPE {
	p := new(MIMC_MSG_TYPE)
	*p = x
	return p
}

func (x MIMC_MSG_TYPE) String() string {
	return proto.EnumName(MIMC_MSG_TYPE_name, int32(x))
}

func (x *MIMC_MSG_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MIMC_MSG_TYPE_value, data, "MIMC_MSG_TYPE")
	if err != nil {
		return err
	}
	*x = MIMC_MSG_TYPE(value)
	return nil
}

func (MIMC_MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{1}
}

type UC_MSG_TYPE int32

const (
	UC_MSG_TYPE_PING                    UC_MSG_TYPE = 1
	UC_MSG_TYPE_PONG                    UC_MSG_TYPE = 2
	UC_MSG_TYPE_JOIN                    UC_MSG_TYPE = 3
	UC_MSG_TYPE_JOIN_RESP               UC_MSG_TYPE = 4
	UC_MSG_TYPE_QUIT                    UC_MSG_TYPE = 5
	UC_MSG_TYPE_QUIT_RESP               UC_MSG_TYPE = 6
	UC_MSG_TYPE_SEQ_ACK                 UC_MSG_TYPE = 7
	UC_MSG_TYPE_MESSAGE                 UC_MSG_TYPE = 8
	UC_MSG_TYPE_MESSAGE_LIST            UC_MSG_TYPE = 9
	UC_MSG_TYPE_DISMISS                 UC_MSG_TYPE = 10
	UC_MSG_TYPE_QUERY_ONLINE_USERS      UC_MSG_TYPE = 11
	UC_MSG_TYPE_QUERY_ONLINE_USERS_RESP UC_MSG_TYPE = 12
)

var UC_MSG_TYPE_name = map[int32]string{
	1:  "PING",
	2:  "PONG",
	3:  "JOIN",
	4:  "JOIN_RESP",
	5:  "QUIT",
	6:  "QUIT_RESP",
	7:  "SEQ_ACK",
	8:  "MESSAGE",
	9:  "MESSAGE_LIST",
	10: "DISMISS",
	11: "QUERY_ONLINE_USERS",
	12: "QUERY_ONLINE_USERS_RESP",
}

var UC_MSG_TYPE_value = map[string]int32{
	"PING":                    1,
	"PONG":                    2,
	"JOIN":                    3,
	"JOIN_RESP":               4,
	"QUIT":                    5,
	"QUIT_RESP":               6,
	"SEQ_ACK":                 7,
	"MESSAGE":                 8,
	"MESSAGE_LIST":            9,
	"DISMISS":                 10,
	"QUERY_ONLINE_USERS":      11,
	"QUERY_ONLINE_USERS_RESP": 12,
}

func (x UC_MSG_TYPE) Enum() *UC_MSG_TYPE {
	p := new(UC_MSG_TYPE)
	*p = x
	return p
}

func (x UC_MSG_TYPE) String() string {
	return proto.EnumName(UC_MSG_TYPE_name, int32(x))
}

func (x *UC_MSG_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UC_MSG_TYPE_value, data, "UC_MSG_TYPE")
	if err != nil {
		return err
	}
	*x = UC_MSG_TYPE(value)
	return nil
}

func (UC_MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{2}
}

type FilterRequest struct {
	Id                   *string     `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Packet               *MIMCPacket `protobuf:"bytes,2,req,name=packet" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{0}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *FilterRequest) GetPacket() *MIMCPacket {
	if m != nil {
		return m.Packet
	}
	return nil
}

type FilterResponse struct {
	Id                   *string        `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Type                 *MIMC_MSG_TYPE `protobuf:"varint,2,opt,name=type,enum=mimc.MIMC_MSG_TYPE" json:"type,omitempty"`
	ErrorCode            *ErrorCode     `protobuf:"varint,3,opt,name=errorCode,enum=mimc.ErrorCode" json:"errorCode,omitempty"`
	IsFilter             *bool          `protobuf:"varint,4,opt,name=isFilter" json:"isFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FilterResponse) Reset()         { *m = FilterResponse{} }
func (m *FilterResponse) String() string { return proto.CompactTextString(m) }
func (*FilterResponse) ProtoMessage()    {}
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{1}
}

func (m *FilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterResponse.Unmarshal(m, b)
}
func (m *FilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterResponse.Marshal(b, m, deterministic)
}
func (m *FilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterResponse.Merge(m, src)
}
func (m *FilterResponse) XXX_Size() int {
	return xxx_messageInfo_FilterResponse.Size(m)
}
func (m *FilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterResponse proto.InternalMessageInfo

func (m *FilterResponse) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *FilterResponse) GetType() MIMC_MSG_TYPE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MIMC_MSG_TYPE_P2P_MESSAGE
}

func (m *FilterResponse) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_OK
}

func (m *FilterResponse) GetIsFilter() bool {
	if m != nil && m.IsFilter != nil {
		return *m.IsFilter
	}
	return false
}

// xmq --> seq-msg-storage
type PullMessageRequest struct {
	Uuid                 *uint64  `protobuf:"varint,1,req,name=uuid" json:"uuid,omitempty"`
	Resource             *string  `protobuf:"bytes,2,req,name=resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMessageRequest) Reset()         { *m = PullMessageRequest{} }
func (m *PullMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PullMessageRequest) ProtoMessage()    {}
func (*PullMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{2}
}

func (m *PullMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMessageRequest.Unmarshal(m, b)
}
func (m *PullMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMessageRequest.Marshal(b, m, deterministic)
}
func (m *PullMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMessageRequest.Merge(m, src)
}
func (m *PullMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PullMessageRequest.Size(m)
}
func (m *PullMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullMessageRequest proto.InternalMessageInfo

func (m *PullMessageRequest) GetUuid() uint64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *PullMessageRequest) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

type TopicMessage struct {
	TopicId              *uint64     `protobuf:"varint,1,req,name=topicId" json:"topicId,omitempty"`
	Packet               *MIMCPacket `protobuf:"bytes,2,req,name=packet" json:"packet,omitempty"`
	Uuid                 *int64      `protobuf:"varint,3,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string     `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{3}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

func (m *TopicMessage) GetTopicId() uint64 {
	if m != nil && m.TopicId != nil {
		return *m.TopicId
	}
	return 0
}

func (m *TopicMessage) GetPacket() *MIMCPacket {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *TopicMessage) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *TopicMessage) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

//**AM*************************************
type QueryAppinfoRequest struct {
	AppId                *uint64  `protobuf:"varint,1,req,name=appId" json:"appId,omitempty"`
	Context              *string  `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAppinfoRequest) Reset()         { *m = QueryAppinfoRequest{} }
func (m *QueryAppinfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAppinfoRequest) ProtoMessage()    {}
func (*QueryAppinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{4}
}

func (m *QueryAppinfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAppinfoRequest.Unmarshal(m, b)
}
func (m *QueryAppinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAppinfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryAppinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAppinfoRequest.Merge(m, src)
}
func (m *QueryAppinfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAppinfoRequest.Size(m)
}
func (m *QueryAppinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAppinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAppinfoRequest proto.InternalMessageInfo

func (m *QueryAppinfoRequest) GetAppId() uint64 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *QueryAppinfoRequest) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

type Appinfo struct {
	AppId                 *uint64  `protobuf:"varint,1,req,name=appId" json:"appId,omitempty"`
	MsgCallbackUrl        *string  `protobuf:"bytes,2,opt,name=msgCallbackUrl" json:"msgCallbackUrl,omitempty"`
	OfflineMsgCallbackUrl *string  `protobuf:"bytes,3,opt,name=offlineMsgCallbackUrl" json:"offlineMsgCallbackUrl,omitempty"`
	UuidTTL               *uint64  `protobuf:"varint,4,opt,name=uuidTTL" json:"uuidTTL,omitempty"`
	Context               *string  `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
	MessageFilter         *string  `protobuf:"bytes,6,opt,name=messageFilter" json:"messageFilter,omitempty"`
	UcMsgCallbackUrl      *string  `protobuf:"bytes,7,opt,name=ucMsgCallbackUrl" json:"ucMsgCallbackUrl,omitempty"`
	EnableBlacklist       *bool    `protobuf:"varint,8,opt,name=enableBlacklist" json:"enableBlacklist,omitempty"`
	TopicMemberCount      *int64   `protobuf:"varint,9,opt,name=topicMemberCount" json:"topicMemberCount,omitempty"`
	EnableAntiSpam        *bool    `protobuf:"varint,10,opt,name=enableAntiSpam" json:"enableAntiSpam,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Appinfo) Reset()         { *m = Appinfo{} }
func (m *Appinfo) String() string { return proto.CompactTextString(m) }
func (*Appinfo) ProtoMessage()    {}
func (*Appinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{5}
}

func (m *Appinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Appinfo.Unmarshal(m, b)
}
func (m *Appinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Appinfo.Marshal(b, m, deterministic)
}
func (m *Appinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Appinfo.Merge(m, src)
}
func (m *Appinfo) XXX_Size() int {
	return xxx_messageInfo_Appinfo.Size(m)
}
func (m *Appinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Appinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Appinfo proto.InternalMessageInfo

func (m *Appinfo) GetAppId() uint64 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *Appinfo) GetMsgCallbackUrl() string {
	if m != nil && m.MsgCallbackUrl != nil {
		return *m.MsgCallbackUrl
	}
	return ""
}

func (m *Appinfo) GetOfflineMsgCallbackUrl() string {
	if m != nil && m.OfflineMsgCallbackUrl != nil {
		return *m.OfflineMsgCallbackUrl
	}
	return ""
}

func (m *Appinfo) GetUuidTTL() uint64 {
	if m != nil && m.UuidTTL != nil {
		return *m.UuidTTL
	}
	return 0
}

func (m *Appinfo) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

func (m *Appinfo) GetMessageFilter() string {
	if m != nil && m.MessageFilter != nil {
		return *m.MessageFilter
	}
	return ""
}

func (m *Appinfo) GetUcMsgCallbackUrl() string {
	if m != nil && m.UcMsgCallbackUrl != nil {
		return *m.UcMsgCallbackUrl
	}
	return ""
}

func (m *Appinfo) GetEnableBlacklist() bool {
	if m != nil && m.EnableBlacklist != nil {
		return *m.EnableBlacklist
	}
	return false
}

func (m *Appinfo) GetTopicMemberCount() int64 {
	if m != nil && m.TopicMemberCount != nil {
		return *m.TopicMemberCount
	}
	return 0
}

func (m *Appinfo) GetEnableAntiSpam() bool {
	if m != nil && m.EnableAntiSpam != nil {
		return *m.EnableAntiSpam
	}
	return false
}

//*
// MIMCPacket为packetv6中的payload
type MIMCPacket struct {
	PacketId             *string        `protobuf:"bytes,1,opt,name=packetId" json:"packetId,omitempty"`
	Package              *string        `protobuf:"bytes,2,opt,name=package" json:"package,omitempty"`
	Sequence             *int64         `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	Type                 *MIMC_MSG_TYPE `protobuf:"varint,4,opt,name=type,enum=mimc.MIMC_MSG_TYPE" json:"type,omitempty"`
	Payload              []byte         `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
	Timestamp            *int64         `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MIMCPacket) Reset()         { *m = MIMCPacket{} }
func (m *MIMCPacket) String() string { return proto.CompactTextString(m) }
func (*MIMCPacket) ProtoMessage()    {}
func (*MIMCPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{6}
}

func (m *MIMCPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCPacket.Unmarshal(m, b)
}
func (m *MIMCPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCPacket.Marshal(b, m, deterministic)
}
func (m *MIMCPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCPacket.Merge(m, src)
}
func (m *MIMCPacket) XXX_Size() int {
	return xxx_messageInfo_MIMCPacket.Size(m)
}
func (m *MIMCPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCPacket.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCPacket proto.InternalMessageInfo

func (m *MIMCPacket) GetPacketId() string {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return ""
}

func (m *MIMCPacket) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

func (m *MIMCPacket) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *MIMCPacket) GetType() MIMC_MSG_TYPE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MIMC_MSG_TYPE_P2P_MESSAGE
}

func (m *MIMCPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MIMCPacket) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

//**************************下行消息************************
type MIMCPacketList struct {
	Uuid                 *int64        `protobuf:"varint,1,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string       `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	MaxSequence          *int64        `protobuf:"varint,3,opt,name=maxSequence" json:"maxSequence,omitempty"`
	Packets              []*MIMCPacket `protobuf:"bytes,4,rep,name=packets" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MIMCPacketList) Reset()         { *m = MIMCPacketList{} }
func (m *MIMCPacketList) String() string { return proto.CompactTextString(m) }
func (*MIMCPacketList) ProtoMessage()    {}
func (*MIMCPacketList) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{7}
}

func (m *MIMCPacketList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCPacketList.Unmarshal(m, b)
}
func (m *MIMCPacketList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCPacketList.Marshal(b, m, deterministic)
}
func (m *MIMCPacketList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCPacketList.Merge(m, src)
}
func (m *MIMCPacketList) XXX_Size() int {
	return xxx_messageInfo_MIMCPacketList.Size(m)
}
func (m *MIMCPacketList) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCPacketList.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCPacketList proto.InternalMessageInfo

func (m *MIMCPacketList) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *MIMCPacketList) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

func (m *MIMCPacketList) GetMaxSequence() int64 {
	if m != nil && m.MaxSequence != nil {
		return *m.MaxSequence
	}
	return 0
}

func (m *MIMCPacketList) GetPackets() []*MIMCPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

type MIMCPacketAck struct {
	PacketId             *string  `protobuf:"bytes,1,opt,name=packetId" json:"packetId,omitempty"`
	Uuid                 *int64   `protobuf:"varint,2,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string  `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Sequence             *int64   `protobuf:"varint,4,opt,name=sequence" json:"sequence,omitempty"`
	Timestamp            *int64   `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Package              *string  `protobuf:"bytes,6,opt,name=package" json:"package,omitempty"`
	ErrorMsg             *string  `protobuf:"bytes,7,opt,name=errorMsg" json:"errorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MIMCPacketAck) Reset()         { *m = MIMCPacketAck{} }
func (m *MIMCPacketAck) String() string { return proto.CompactTextString(m) }
func (*MIMCPacketAck) ProtoMessage()    {}
func (*MIMCPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{8}
}

func (m *MIMCPacketAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCPacketAck.Unmarshal(m, b)
}
func (m *MIMCPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCPacketAck.Marshal(b, m, deterministic)
}
func (m *MIMCPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCPacketAck.Merge(m, src)
}
func (m *MIMCPacketAck) XXX_Size() int {
	return xxx_messageInfo_MIMCPacketAck.Size(m)
}
func (m *MIMCPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCPacketAck proto.InternalMessageInfo

func (m *MIMCPacketAck) GetPacketId() string {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return ""
}

func (m *MIMCPacketAck) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *MIMCPacketAck) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

func (m *MIMCPacketAck) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *MIMCPacketAck) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *MIMCPacketAck) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

func (m *MIMCPacketAck) GetErrorMsg() string {
	if m != nil && m.ErrorMsg != nil {
		return *m.ErrorMsg
	}
	return ""
}

//**************************上行消息************************
type MIMCP2PMessage struct {
	From                 *MIMCUser `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   *MIMCUser `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Payload              []byte    `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	IsStore              *bool     `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	BizType              *string   `protobuf:"bytes,5,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MIMCP2PMessage) Reset()         { *m = MIMCP2PMessage{} }
func (m *MIMCP2PMessage) String() string { return proto.CompactTextString(m) }
func (*MIMCP2PMessage) ProtoMessage()    {}
func (*MIMCP2PMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{9}
}

func (m *MIMCP2PMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCP2PMessage.Unmarshal(m, b)
}
func (m *MIMCP2PMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCP2PMessage.Marshal(b, m, deterministic)
}
func (m *MIMCP2PMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCP2PMessage.Merge(m, src)
}
func (m *MIMCP2PMessage) XXX_Size() int {
	return xxx_messageInfo_MIMCP2PMessage.Size(m)
}
func (m *MIMCP2PMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCP2PMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCP2PMessage proto.InternalMessageInfo

func (m *MIMCP2PMessage) GetFrom() *MIMCUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MIMCP2PMessage) GetTo() *MIMCUser {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MIMCP2PMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MIMCP2PMessage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *MIMCP2PMessage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

type MIMCP2TMessage struct {
	From                 *MIMCUser  `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   *MIMCGroup `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Payload              []byte     `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	IsStore              *bool      `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	BizType              *string    `protobuf:"bytes,5,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MIMCP2TMessage) Reset()         { *m = MIMCP2TMessage{} }
func (m *MIMCP2TMessage) String() string { return proto.CompactTextString(m) }
func (*MIMCP2TMessage) ProtoMessage()    {}
func (*MIMCP2TMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{10}
}

func (m *MIMCP2TMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCP2TMessage.Unmarshal(m, b)
}
func (m *MIMCP2TMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCP2TMessage.Marshal(b, m, deterministic)
}
func (m *MIMCP2TMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCP2TMessage.Merge(m, src)
}
func (m *MIMCP2TMessage) XXX_Size() int {
	return xxx_messageInfo_MIMCP2TMessage.Size(m)
}
func (m *MIMCP2TMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCP2TMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCP2TMessage proto.InternalMessageInfo

func (m *MIMCP2TMessage) GetFrom() *MIMCUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MIMCP2TMessage) GetTo() *MIMCGroup {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MIMCP2TMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MIMCP2TMessage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *MIMCP2TMessage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

type MIMCSequenceAck struct {
	Uuid                 *int64   `protobuf:"varint,1,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string  `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	Sequence             *int64   `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MIMCSequenceAck) Reset()         { *m = MIMCSequenceAck{} }
func (m *MIMCSequenceAck) String() string { return proto.CompactTextString(m) }
func (*MIMCSequenceAck) ProtoMessage()    {}
func (*MIMCSequenceAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{11}
}

func (m *MIMCSequenceAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCSequenceAck.Unmarshal(m, b)
}
func (m *MIMCSequenceAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCSequenceAck.Marshal(b, m, deterministic)
}
func (m *MIMCSequenceAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCSequenceAck.Merge(m, src)
}
func (m *MIMCSequenceAck) XXX_Size() int {
	return xxx_messageInfo_MIMCSequenceAck.Size(m)
}
func (m *MIMCSequenceAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCSequenceAck.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCSequenceAck proto.InternalMessageInfo

func (m *MIMCSequenceAck) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *MIMCSequenceAck) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

func (m *MIMCSequenceAck) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

type MIMCPull struct {
	Uuid                 *int64   `protobuf:"varint,1,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string  `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MIMCPull) Reset()         { *m = MIMCPull{} }
func (m *MIMCPull) String() string { return proto.CompactTextString(m) }
func (*MIMCPull) ProtoMessage()    {}
func (*MIMCPull) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{12}
}

func (m *MIMCPull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCPull.Unmarshal(m, b)
}
func (m *MIMCPull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCPull.Marshal(b, m, deterministic)
}
func (m *MIMCPull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCPull.Merge(m, src)
}
func (m *MIMCPull) XXX_Size() int {
	return xxx_messageInfo_MIMCPull.Size(m)
}
func (m *MIMCPull) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCPull.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCPull proto.InternalMessageInfo

func (m *MIMCPull) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *MIMCPull) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

// 单聊推送
type P2PPushMesage struct {
	From                 *MIMCUser   `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   []*MIMCUser `protobuf:"bytes,2,rep,name=to" json:"to,omitempty"`
	Payload              []byte      `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	IsStore              *bool       `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	BizType              *string     `protobuf:"bytes,5,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *P2PPushMesage) Reset()         { *m = P2PPushMesage{} }
func (m *P2PPushMesage) String() string { return proto.CompactTextString(m) }
func (*P2PPushMesage) ProtoMessage()    {}
func (*P2PPushMesage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{13}
}

func (m *P2PPushMesage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PPushMesage.Unmarshal(m, b)
}
func (m *P2PPushMesage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PPushMesage.Marshal(b, m, deterministic)
}
func (m *P2PPushMesage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PPushMesage.Merge(m, src)
}
func (m *P2PPushMesage) XXX_Size() int {
	return xxx_messageInfo_P2PPushMesage.Size(m)
}
func (m *P2PPushMesage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PPushMesage.DiscardUnknown(m)
}

var xxx_messageInfo_P2PPushMesage proto.InternalMessageInfo

func (m *P2PPushMesage) GetFrom() *MIMCUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *P2PPushMesage) GetTo() []*MIMCUser {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *P2PPushMesage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *P2PPushMesage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *P2PPushMesage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

// 普通群聊推送
type P2TPushMesage struct {
	From                 *MIMCUser    `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   []*MIMCGroup `protobuf:"bytes,2,rep,name=to" json:"to,omitempty"`
	Payload              []byte       `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	IsStore              *bool        `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	BizType              *string      `protobuf:"bytes,5,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *P2TPushMesage) Reset()         { *m = P2TPushMesage{} }
func (m *P2TPushMesage) String() string { return proto.CompactTextString(m) }
func (*P2TPushMesage) ProtoMessage()    {}
func (*P2TPushMesage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{14}
}

func (m *P2TPushMesage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2TPushMesage.Unmarshal(m, b)
}
func (m *P2TPushMesage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2TPushMesage.Marshal(b, m, deterministic)
}
func (m *P2TPushMesage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2TPushMesage.Merge(m, src)
}
func (m *P2TPushMesage) XXX_Size() int {
	return xxx_messageInfo_P2TPushMesage.Size(m)
}
func (m *P2TPushMesage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2TPushMesage.DiscardUnknown(m)
}

var xxx_messageInfo_P2TPushMesage proto.InternalMessageInfo

func (m *P2TPushMesage) GetFrom() *MIMCUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *P2TPushMesage) GetTo() []*MIMCGroup {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *P2TPushMesage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *P2TPushMesage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *P2TPushMesage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

//**************************公共定义************************
type MIMCUser struct {
	AppId                *int64   `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	AppAccount           *string  `protobuf:"bytes,2,opt,name=appAccount" json:"appAccount,omitempty"`
	Uuid                 *int64   `protobuf:"varint,3,opt,name=uuid" json:"uuid,omitempty"`
	Resource             *string  `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MIMCUser) Reset()         { *m = MIMCUser{} }
func (m *MIMCUser) String() string { return proto.CompactTextString(m) }
func (*MIMCUser) ProtoMessage()    {}
func (*MIMCUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{15}
}

func (m *MIMCUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCUser.Unmarshal(m, b)
}
func (m *MIMCUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCUser.Marshal(b, m, deterministic)
}
func (m *MIMCUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCUser.Merge(m, src)
}
func (m *MIMCUser) XXX_Size() int {
	return xxx_messageInfo_MIMCUser.Size(m)
}
func (m *MIMCUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCUser.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCUser proto.InternalMessageInfo

func (m *MIMCUser) GetAppId() int64 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *MIMCUser) GetAppAccount() string {
	if m != nil && m.AppAccount != nil {
		return *m.AppAccount
	}
	return ""
}

func (m *MIMCUser) GetUuid() int64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *MIMCUser) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

type MIMCGroup struct {
	AppId                *int64   `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	TopicId              *int64   `protobuf:"varint,2,opt,name=topicId" json:"topicId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MIMCGroup) Reset()         { *m = MIMCGroup{} }
func (m *MIMCGroup) String() string { return proto.CompactTextString(m) }
func (*MIMCGroup) ProtoMessage()    {}
func (*MIMCGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{16}
}

func (m *MIMCGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIMCGroup.Unmarshal(m, b)
}
func (m *MIMCGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIMCGroup.Marshal(b, m, deterministic)
}
func (m *MIMCGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIMCGroup.Merge(m, src)
}
func (m *MIMCGroup) XXX_Size() int {
	return xxx_messageInfo_MIMCGroup.Size(m)
}
func (m *MIMCGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MIMCGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MIMCGroup proto.InternalMessageInfo

func (m *MIMCGroup) GetAppId() int64 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *MIMCGroup) GetTopicId() int64 {
	if m != nil && m.TopicId != nil {
		return *m.TopicId
	}
	return 0
}

type UCGroup struct {
	AppId                *int64   `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	TopicId              *int64   `protobuf:"varint,2,opt,name=topicId" json:"topicId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCGroup) Reset()         { *m = UCGroup{} }
func (m *UCGroup) String() string { return proto.CompactTextString(m) }
func (*UCGroup) ProtoMessage()    {}
func (*UCGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{17}
}

func (m *UCGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCGroup.Unmarshal(m, b)
}
func (m *UCGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCGroup.Marshal(b, m, deterministic)
}
func (m *UCGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCGroup.Merge(m, src)
}
func (m *UCGroup) XXX_Size() int {
	return xxx_messageInfo_UCGroup.Size(m)
}
func (m *UCGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UCGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UCGroup proto.InternalMessageInfo

func (m *UCGroup) GetAppId() int64 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *UCGroup) GetTopicId() int64 {
	if m != nil && m.TopicId != nil {
		return *m.TopicId
	}
	return 0
}

//*************************UnlimitedChat*************************
type UCPacket struct {
	User                 *MIMCUser    `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Type                 *UC_MSG_TYPE `protobuf:"varint,2,req,name=type,enum=mimc.UC_MSG_TYPE" json:"type,omitempty"`
	Payload              []byte       `protobuf:"bytes,3,req,name=payload" json:"payload,omitempty"`
	PacketId             *string      `protobuf:"bytes,4,req,name=packetId" json:"packetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UCPacket) Reset()         { *m = UCPacket{} }
func (m *UCPacket) String() string { return proto.CompactTextString(m) }
func (*UCPacket) ProtoMessage()    {}
func (*UCPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{18}
}

func (m *UCPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCPacket.Unmarshal(m, b)
}
func (m *UCPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCPacket.Marshal(b, m, deterministic)
}
func (m *UCPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCPacket.Merge(m, src)
}
func (m *UCPacket) XXX_Size() int {
	return xxx_messageInfo_UCPacket.Size(m)
}
func (m *UCPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_UCPacket.DiscardUnknown(m)
}

var xxx_messageInfo_UCPacket proto.InternalMessageInfo

func (m *UCPacket) GetUser() *MIMCUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UCPacket) GetType() UC_MSG_TYPE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return UC_MSG_TYPE_PING
}

func (m *UCPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UCPacket) GetPacketId() string {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return ""
}

type UCExchange struct {
	FeInfo               *FeInfo   `protobuf:"bytes,1,opt,name=feInfo" json:"feInfo,omitempty"`
	Packet               *UCPacket `protobuf:"bytes,2,req,name=packet" json:"packet,omitempty"`
	Package              *string   `protobuf:"bytes,3,req,name=package" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UCExchange) Reset()         { *m = UCExchange{} }
func (m *UCExchange) String() string { return proto.CompactTextString(m) }
func (*UCExchange) ProtoMessage()    {}
func (*UCExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{19}
}

func (m *UCExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCExchange.Unmarshal(m, b)
}
func (m *UCExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCExchange.Marshal(b, m, deterministic)
}
func (m *UCExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCExchange.Merge(m, src)
}
func (m *UCExchange) XXX_Size() int {
	return xxx_messageInfo_UCExchange.Size(m)
}
func (m *UCExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_UCExchange.DiscardUnknown(m)
}

var xxx_messageInfo_UCExchange proto.InternalMessageInfo

func (m *UCExchange) GetFeInfo() *FeInfo {
	if m != nil {
		return m.FeInfo
	}
	return nil
}

func (m *UCExchange) GetPacket() *UCPacket {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *UCExchange) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

type UCJoin struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCJoin) Reset()         { *m = UCJoin{} }
func (m *UCJoin) String() string { return proto.CompactTextString(m) }
func (*UCJoin) ProtoMessage()    {}
func (*UCJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{20}
}

func (m *UCJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCJoin.Unmarshal(m, b)
}
func (m *UCJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCJoin.Marshal(b, m, deterministic)
}
func (m *UCJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCJoin.Merge(m, src)
}
func (m *UCJoin) XXX_Size() int {
	return xxx_messageInfo_UCJoin.Size(m)
}
func (m *UCJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_UCJoin.DiscardUnknown(m)
}

var xxx_messageInfo_UCJoin proto.InternalMessageInfo

func (m *UCJoin) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

type UCJoinResp struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCJoinResp) Reset()         { *m = UCJoinResp{} }
func (m *UCJoinResp) String() string { return proto.CompactTextString(m) }
func (*UCJoinResp) ProtoMessage()    {}
func (*UCJoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{21}
}

func (m *UCJoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCJoinResp.Unmarshal(m, b)
}
func (m *UCJoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCJoinResp.Marshal(b, m, deterministic)
}
func (m *UCJoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCJoinResp.Merge(m, src)
}
func (m *UCJoinResp) XXX_Size() int {
	return xxx_messageInfo_UCJoinResp.Size(m)
}
func (m *UCJoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UCJoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_UCJoinResp proto.InternalMessageInfo

func (m *UCJoinResp) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCJoinResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *UCJoinResp) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type UCQuit struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCQuit) Reset()         { *m = UCQuit{} }
func (m *UCQuit) String() string { return proto.CompactTextString(m) }
func (*UCQuit) ProtoMessage()    {}
func (*UCQuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{22}
}

func (m *UCQuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCQuit.Unmarshal(m, b)
}
func (m *UCQuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCQuit.Marshal(b, m, deterministic)
}
func (m *UCQuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCQuit.Merge(m, src)
}
func (m *UCQuit) XXX_Size() int {
	return xxx_messageInfo_UCQuit.Size(m)
}
func (m *UCQuit) XXX_DiscardUnknown() {
	xxx_messageInfo_UCQuit.DiscardUnknown(m)
}

var xxx_messageInfo_UCQuit proto.InternalMessageInfo

func (m *UCQuit) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

type UCQuitResp struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCQuitResp) Reset()         { *m = UCQuitResp{} }
func (m *UCQuitResp) String() string { return proto.CompactTextString(m) }
func (*UCQuitResp) ProtoMessage()    {}
func (*UCQuitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{23}
}

func (m *UCQuitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCQuitResp.Unmarshal(m, b)
}
func (m *UCQuitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCQuitResp.Marshal(b, m, deterministic)
}
func (m *UCQuitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCQuitResp.Merge(m, src)
}
func (m *UCQuitResp) XXX_Size() int {
	return xxx_messageInfo_UCQuitResp.Size(m)
}
func (m *UCQuitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UCQuitResp.DiscardUnknown(m)
}

var xxx_messageInfo_UCQuitResp proto.InternalMessageInfo

func (m *UCQuitResp) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCQuitResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *UCQuitResp) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type UCPing struct {
	Group                []*UCGroup `protobuf:"bytes,1,rep,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UCPing) Reset()         { *m = UCPing{} }
func (m *UCPing) String() string { return proto.CompactTextString(m) }
func (*UCPing) ProtoMessage()    {}
func (*UCPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{24}
}

func (m *UCPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCPing.Unmarshal(m, b)
}
func (m *UCPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCPing.Marshal(b, m, deterministic)
}
func (m *UCPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCPing.Merge(m, src)
}
func (m *UCPing) XXX_Size() int {
	return xxx_messageInfo_UCPing.Size(m)
}
func (m *UCPing) XXX_DiscardUnknown() {
	xxx_messageInfo_UCPing.DiscardUnknown(m)
}

var xxx_messageInfo_UCPing proto.InternalMessageInfo

func (m *UCPing) GetGroup() []*UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

type UCMessage struct {
	Group                *UCGroup  `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Payload              []byte    `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	Sequence             *int64    `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	IsStore              *bool     `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	User                 *MIMCUser `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Timestamp            *int64    `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	PacketId             *string   `protobuf:"bytes,7,opt,name=packetId" json:"packetId,omitempty"`
	BizType              *string   `protobuf:"bytes,8,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UCMessage) Reset()         { *m = UCMessage{} }
func (m *UCMessage) String() string { return proto.CompactTextString(m) }
func (*UCMessage) ProtoMessage()    {}
func (*UCMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{25}
}

func (m *UCMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCMessage.Unmarshal(m, b)
}
func (m *UCMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCMessage.Marshal(b, m, deterministic)
}
func (m *UCMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCMessage.Merge(m, src)
}
func (m *UCMessage) XXX_Size() int {
	return xxx_messageInfo_UCMessage.Size(m)
}
func (m *UCMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UCMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UCMessage proto.InternalMessageInfo

func (m *UCMessage) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UCMessage) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *UCMessage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *UCMessage) GetUser() *MIMCUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UCMessage) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *UCMessage) GetPacketId() string {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return ""
}

func (m *UCMessage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

// for push
type UCPushMessage struct {
	User                 *MIMCUser  `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Group                []*UCGroup `protobuf:"bytes,2,rep,name=group" json:"group,omitempty"`
	Payloads             [][]byte   `protobuf:"bytes,3,rep,name=payloads" json:"payloads,omitempty"`
	IsStore              *bool      `protobuf:"varint,4,opt,name=isStore" json:"isStore,omitempty"`
	Timestamp            *int64     `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	PacketId             *string    `protobuf:"bytes,6,opt,name=packetId" json:"packetId,omitempty"`
	BizType              *string    `protobuf:"bytes,7,opt,name=bizType" json:"bizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UCPushMessage) Reset()         { *m = UCPushMessage{} }
func (m *UCPushMessage) String() string { return proto.CompactTextString(m) }
func (*UCPushMessage) ProtoMessage()    {}
func (*UCPushMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{26}
}

func (m *UCPushMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCPushMessage.Unmarshal(m, b)
}
func (m *UCPushMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCPushMessage.Marshal(b, m, deterministic)
}
func (m *UCPushMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCPushMessage.Merge(m, src)
}
func (m *UCPushMessage) XXX_Size() int {
	return xxx_messageInfo_UCPushMessage.Size(m)
}
func (m *UCPushMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UCPushMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UCPushMessage proto.InternalMessageInfo

func (m *UCPushMessage) GetUser() *MIMCUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UCPushMessage) GetGroup() []*UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCPushMessage) GetPayloads() [][]byte {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *UCPushMessage) GetIsStore() bool {
	if m != nil && m.IsStore != nil {
		return *m.IsStore
	}
	return false
}

func (m *UCPushMessage) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *UCPushMessage) GetPacketId() string {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return ""
}

func (m *UCPushMessage) GetBizType() string {
	if m != nil && m.BizType != nil {
		return *m.BizType
	}
	return ""
}

type UCMessageList struct {
	Group                *UCGroup     `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Message              []*UCMessage `protobuf:"bytes,2,rep,name=message" json:"message,omitempty"`
	MaxSequence          *int64       `protobuf:"varint,3,opt,name=maxSequence" json:"maxSequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UCMessageList) Reset()         { *m = UCMessageList{} }
func (m *UCMessageList) String() string { return proto.CompactTextString(m) }
func (*UCMessageList) ProtoMessage()    {}
func (*UCMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{27}
}

func (m *UCMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCMessageList.Unmarshal(m, b)
}
func (m *UCMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCMessageList.Marshal(b, m, deterministic)
}
func (m *UCMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCMessageList.Merge(m, src)
}
func (m *UCMessageList) XXX_Size() int {
	return xxx_messageInfo_UCMessageList.Size(m)
}
func (m *UCMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_UCMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_UCMessageList proto.InternalMessageInfo

func (m *UCMessageList) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCMessageList) GetMessage() []*UCMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *UCMessageList) GetMaxSequence() int64 {
	if m != nil && m.MaxSequence != nil {
		return *m.MaxSequence
	}
	return 0
}

//每个Group一个ack
type UCSequenceAck struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Sequence             *int64   `protobuf:"varint,2,req,name=sequence" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCSequenceAck) Reset()         { *m = UCSequenceAck{} }
func (m *UCSequenceAck) String() string { return proto.CompactTextString(m) }
func (*UCSequenceAck) ProtoMessage()    {}
func (*UCSequenceAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{28}
}

func (m *UCSequenceAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCSequenceAck.Unmarshal(m, b)
}
func (m *UCSequenceAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCSequenceAck.Marshal(b, m, deterministic)
}
func (m *UCSequenceAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCSequenceAck.Merge(m, src)
}
func (m *UCSequenceAck) XXX_Size() int {
	return xxx_messageInfo_UCSequenceAck.Size(m)
}
func (m *UCSequenceAck) XXX_DiscardUnknown() {
	xxx_messageInfo_UCSequenceAck.DiscardUnknown(m)
}

var xxx_messageInfo_UCSequenceAck proto.InternalMessageInfo

func (m *UCSequenceAck) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCSequenceAck) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

type UCDismiss struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCDismiss) Reset()         { *m = UCDismiss{} }
func (m *UCDismiss) String() string { return proto.CompactTextString(m) }
func (*UCDismiss) ProtoMessage()    {}
func (*UCDismiss) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{29}
}

func (m *UCDismiss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCDismiss.Unmarshal(m, b)
}
func (m *UCDismiss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCDismiss.Marshal(b, m, deterministic)
}
func (m *UCDismiss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCDismiss.Merge(m, src)
}
func (m *UCDismiss) XXX_Size() int {
	return xxx_messageInfo_UCDismiss.Size(m)
}
func (m *UCDismiss) XXX_DiscardUnknown() {
	xxx_messageInfo_UCDismiss.DiscardUnknown(m)
}

var xxx_messageInfo_UCDismiss proto.InternalMessageInfo

func (m *UCDismiss) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

type UCQueryOnlineUsers struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCQueryOnlineUsers) Reset()         { *m = UCQueryOnlineUsers{} }
func (m *UCQueryOnlineUsers) String() string { return proto.CompactTextString(m) }
func (*UCQueryOnlineUsers) ProtoMessage()    {}
func (*UCQueryOnlineUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{30}
}

func (m *UCQueryOnlineUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCQueryOnlineUsers.Unmarshal(m, b)
}
func (m *UCQueryOnlineUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCQueryOnlineUsers.Marshal(b, m, deterministic)
}
func (m *UCQueryOnlineUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCQueryOnlineUsers.Merge(m, src)
}
func (m *UCQueryOnlineUsers) XXX_Size() int {
	return xxx_messageInfo_UCQueryOnlineUsers.Size(m)
}
func (m *UCQueryOnlineUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_UCQueryOnlineUsers.DiscardUnknown(m)
}

var xxx_messageInfo_UCQueryOnlineUsers proto.InternalMessageInfo

func (m *UCQueryOnlineUsers) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

type UCQueryOnlineUsersResp struct {
	Group                *UCGroup `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	UserCount            *int64   `protobuf:"varint,2,req,name=userCount" json:"userCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UCQueryOnlineUsersResp) Reset()         { *m = UCQueryOnlineUsersResp{} }
func (m *UCQueryOnlineUsersResp) String() string { return proto.CompactTextString(m) }
func (*UCQueryOnlineUsersResp) ProtoMessage()    {}
func (*UCQueryOnlineUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{31}
}

func (m *UCQueryOnlineUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UCQueryOnlineUsersResp.Unmarshal(m, b)
}
func (m *UCQueryOnlineUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UCQueryOnlineUsersResp.Marshal(b, m, deterministic)
}
func (m *UCQueryOnlineUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UCQueryOnlineUsersResp.Merge(m, src)
}
func (m *UCQueryOnlineUsersResp) XXX_Size() int {
	return xxx_messageInfo_UCQueryOnlineUsersResp.Size(m)
}
func (m *UCQueryOnlineUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UCQueryOnlineUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_UCQueryOnlineUsersResp proto.InternalMessageInfo

func (m *UCQueryOnlineUsersResp) GetGroup() *UCGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UCQueryOnlineUsersResp) GetUserCount() int64 {
	if m != nil && m.UserCount != nil {
		return *m.UserCount
	}
	return 0
}

// FE 信息以及用户具体服务在 FE session 的信息
type FeInfo struct {
	FeSrcIp              *string  `protobuf:"bytes,1,opt,name=fe_src_ip,json=feSrcIp" json:"fe_src_ip,omitempty"`
	FeSrcPort            *int32   `protobuf:"varint,2,opt,name=fe_src_port,json=feSrcPort" json:"fe_src_port,omitempty"`
	FeThreadId           *int32   `protobuf:"varint,3,opt,name=fe_thread_id,json=feThreadId" json:"fe_thread_id,omitempty"`
	FeUcid               *uint64  `protobuf:"varint,4,opt,name=fe_ucid,json=feUcid" json:"fe_ucid,omitempty"`
	FeSid                *uint64  `protobuf:"varint,5,opt,name=fe_sid,json=feSid" json:"fe_sid,omitempty"`
	FeSeqno              *uint64  `protobuf:"varint,6,opt,name=fe_seqno,json=feSeqno" json:"fe_seqno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeInfo) Reset()         { *m = FeInfo{} }
func (m *FeInfo) String() string { return proto.CompactTextString(m) }
func (*FeInfo) ProtoMessage()    {}
func (*FeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_819b38dc35592d75, []int{32}
}

func (m *FeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeInfo.Unmarshal(m, b)
}
func (m *FeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeInfo.Marshal(b, m, deterministic)
}
func (m *FeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeInfo.Merge(m, src)
}
func (m *FeInfo) XXX_Size() int {
	return xxx_messageInfo_FeInfo.Size(m)
}
func (m *FeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeInfo proto.InternalMessageInfo

func (m *FeInfo) GetFeSrcIp() string {
	if m != nil && m.FeSrcIp != nil {
		return *m.FeSrcIp
	}
	return ""
}

func (m *FeInfo) GetFeSrcPort() int32 {
	if m != nil && m.FeSrcPort != nil {
		return *m.FeSrcPort
	}
	return 0
}

func (m *FeInfo) GetFeThreadId() int32 {
	if m != nil && m.FeThreadId != nil {
		return *m.FeThreadId
	}
	return 0
}

func (m *FeInfo) GetFeUcid() uint64 {
	if m != nil && m.FeUcid != nil {
		return *m.FeUcid
	}
	return 0
}

func (m *FeInfo) GetFeSid() uint64 {
	if m != nil && m.FeSid != nil {
		return *m.FeSid
	}
	return 0
}

func (m *FeInfo) GetFeSeqno() uint64 {
	if m != nil && m.FeSeqno != nil {
		return *m.FeSeqno
	}
	return 0
}

func init() {
	proto.RegisterEnum("mimc.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("mimc.MIMC_MSG_TYPE", MIMC_MSG_TYPE_name, MIMC_MSG_TYPE_value)
	proto.RegisterEnum("mimc.UC_MSG_TYPE", UC_MSG_TYPE_name, UC_MSG_TYPE_value)
	proto.RegisterType((*FilterRequest)(nil), "mimc.FilterRequest")
	proto.RegisterType((*FilterResponse)(nil), "mimc.FilterResponse")
	proto.RegisterType((*PullMessageRequest)(nil), "mimc.PullMessageRequest")
	proto.RegisterType((*TopicMessage)(nil), "mimc.TopicMessage")
	proto.RegisterType((*QueryAppinfoRequest)(nil), "mimc.QueryAppinfoRequest")
	proto.RegisterType((*Appinfo)(nil), "mimc.Appinfo")
	proto.RegisterType((*MIMCPacket)(nil), "mimc.MIMCPacket")
	proto.RegisterType((*MIMCPacketList)(nil), "mimc.MIMCPacketList")
	proto.RegisterType((*MIMCPacketAck)(nil), "mimc.MIMCPacketAck")
	proto.RegisterType((*MIMCP2PMessage)(nil), "mimc.MIMCP2PMessage")
	proto.RegisterType((*MIMCP2TMessage)(nil), "mimc.MIMCP2TMessage")
	proto.RegisterType((*MIMCSequenceAck)(nil), "mimc.MIMCSequenceAck")
	proto.RegisterType((*MIMCPull)(nil), "mimc.MIMCPull")
	proto.RegisterType((*P2PPushMesage)(nil), "mimc.P2PPushMesage")
	proto.RegisterType((*P2TPushMesage)(nil), "mimc.P2TPushMesage")
	proto.RegisterType((*MIMCUser)(nil), "mimc.MIMCUser")
	proto.RegisterType((*MIMCGroup)(nil), "mimc.MIMCGroup")
	proto.RegisterType((*UCGroup)(nil), "mimc.UCGroup")
	proto.RegisterType((*UCPacket)(nil), "mimc.UCPacket")
	proto.RegisterType((*UCExchange)(nil), "mimc.UCExchange")
	proto.RegisterType((*UCJoin)(nil), "mimc.UCJoin")
	proto.RegisterType((*UCJoinResp)(nil), "mimc.UCJoinResp")
	proto.RegisterType((*UCQuit)(nil), "mimc.UCQuit")
	proto.RegisterType((*UCQuitResp)(nil), "mimc.UCQuitResp")
	proto.RegisterType((*UCPing)(nil), "mimc.UCPing")
	proto.RegisterType((*UCMessage)(nil), "mimc.UCMessage")
	proto.RegisterType((*UCPushMessage)(nil), "mimc.UCPushMessage")
	proto.RegisterType((*UCMessageList)(nil), "mimc.UCMessageList")
	proto.RegisterType((*UCSequenceAck)(nil), "mimc.UCSequenceAck")
	proto.RegisterType((*UCDismiss)(nil), "mimc.UCDismiss")
	proto.RegisterType((*UCQueryOnlineUsers)(nil), "mimc.UCQueryOnlineUsers")
	proto.RegisterType((*UCQueryOnlineUsersResp)(nil), "mimc.UCQueryOnlineUsersResp")
	proto.RegisterType((*FeInfo)(nil), "mimc.FeInfo")
}

func init() { proto.RegisterFile("mimc.proto", fileDescriptor_819b38dc35592d75) }

var fileDescriptor_819b38dc35592d75 = []byte{
	// 1518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0xff, 0xf3, 0xa1, 0xd7, 0x48, 0x96, 0xf9, 0xdf, 0xbc, 0xf4, 0xcf, 0x3f, 0x48, 0x04, 0x36,
	0x4d, 0x54, 0x03, 0x31, 0x0a, 0xa3, 0x97, 0xb4, 0x27, 0x45, 0x66, 0x5c, 0x26, 0x7a, 0xd0, 0x7c,
	0x1c, 0x82, 0xa2, 0x20, 0x68, 0x6a, 0xe5, 0x10, 0x96, 0x44, 0x86, 0x0f, 0xc0, 0xee, 0x2d, 0xbd,
	0x16, 0xe8, 0xa9, 0x5f, 0xa0, 0xe9, 0x27, 0xe8, 0xa5, 0xd7, 0xa2, 0xe7, 0x7e, 0x8b, 0x7e, 0x8a,
	0x1e, 0x8b, 0x5d, 0x72, 0x29, 0x4a, 0xb2, 0x1c, 0xb9, 0x40, 0x72, 0xe3, 0xcc, 0xee, 0xce, 0xfe,
	0x66, 0xe6, 0xb7, 0x33, 0x23, 0x01, 0xcc, 0xbc, 0x99, 0xbb, 0x1f, 0x84, 0x7e, 0xec, 0x23, 0x91,
	0x7c, 0xcb, 0x2a, 0xec, 0x3c, 0xf7, 0xa6, 0x31, 0x0e, 0x75, 0xfc, 0x26, 0xc1, 0x51, 0x8c, 0x9a,
	0xc0, 0x7b, 0xe3, 0x16, 0xd7, 0xe6, 0x3b, 0x35, 0x9d, 0xf7, 0xc6, 0xa8, 0x03, 0xe5, 0xc0, 0x71,
	0xcf, 0x70, 0xdc, 0xe2, 0xdb, 0x7c, 0xa7, 0x7e, 0x20, 0xed, 0x53, 0x1b, 0x03, 0x75, 0xd0, 0xd3,
	0xa8, 0x5e, 0xcf, 0xd6, 0xe5, 0x9f, 0x38, 0x68, 0x32, 0x5b, 0x51, 0xe0, 0xcf, 0x23, 0xbc, 0x66,
	0xec, 0x31, 0x88, 0xf1, 0x45, 0x80, 0x5b, 0x7c, 0x9b, 0xeb, 0x34, 0x0f, 0x6e, 0x2c, 0x4c, 0xd9,
	0x03, 0xe3, 0xc8, 0x36, 0x5f, 0x69, 0x8a, 0x4e, 0x37, 0xa0, 0x27, 0x50, 0xc3, 0x61, 0xe8, 0x87,
	0x3d, 0x7f, 0x8c, 0x5b, 0x02, 0xdd, 0xbd, 0x9b, 0xee, 0x56, 0x98, 0x5a, 0x5f, 0xec, 0x40, 0x77,
	0xa1, 0xea, 0x45, 0xe9, 0xdd, 0x2d, 0xb1, 0xcd, 0x75, 0xaa, 0x7a, 0x2e, 0xcb, 0x87, 0x80, 0xb4,
	0x64, 0x3a, 0x1d, 0xe0, 0x28, 0x72, 0x4e, 0x31, 0x73, 0x13, 0x81, 0x98, 0x24, 0x19, 0x36, 0x51,
	0xa7, 0xdf, 0xc4, 0x4a, 0x88, 0x23, 0x3f, 0x09, 0x5d, 0x4c, 0x9d, 0xad, 0xe9, 0xb9, 0x2c, 0x7f,
	0xcf, 0x41, 0xc3, 0xf4, 0x03, 0xcf, 0xcd, 0xec, 0xa0, 0x16, 0x54, 0x62, 0x22, 0xab, 0xcc, 0x06,
	0x13, 0xb7, 0x8f, 0x58, 0x0e, 0x82, 0x38, 0x28, 0x5c, 0x02, 0x82, 0xb8, 0x52, 0x04, 0xa1, 0xc0,
	0x8d, 0xe3, 0x04, 0x87, 0x17, 0xdd, 0x20, 0xf0, 0xe6, 0x13, 0x9f, 0xf9, 0x72, 0x13, 0x4a, 0x4e,
	0x10, 0xe4, 0x40, 0x52, 0x81, 0x00, 0x74, 0xfd, 0x79, 0x8c, 0xcf, 0x63, 0x1a, 0xee, 0x9a, 0xce,
	0x44, 0xf9, 0xad, 0x00, 0x95, 0xcc, 0xc4, 0x86, 0xb3, 0x8f, 0xa0, 0x39, 0x8b, 0x4e, 0x7b, 0xce,
	0x74, 0x7a, 0xe2, 0xb8, 0x67, 0x56, 0x38, 0xcd, 0x4c, 0xac, 0x68, 0xd1, 0x17, 0x70, 0xcb, 0x9f,
	0x4c, 0xa6, 0xde, 0x1c, 0x0f, 0x96, 0xb7, 0x0b, 0x74, 0xfb, 0xe5, 0x8b, 0x04, 0x19, 0x71, 0xd5,
	0x34, 0xfb, 0xd4, 0x43, 0x51, 0x67, 0x62, 0x11, 0x73, 0x69, 0x09, 0x33, 0x7a, 0x08, 0x3b, 0xb3,
	0x34, 0xf2, 0x59, 0x9a, 0xcb, 0x74, 0x7d, 0x59, 0x89, 0xf6, 0x40, 0x4a, 0xdc, 0x15, 0x28, 0x15,
	0xba, 0x71, 0x4d, 0x8f, 0x3a, 0xb0, 0x8b, 0xe7, 0xce, 0xc9, 0x14, 0x3f, 0x9b, 0x3a, 0xee, 0xd9,
	0xd4, 0x8b, 0xe2, 0x56, 0x95, 0x52, 0x67, 0x55, 0x4d, 0xac, 0xc6, 0x69, 0xea, 0x67, 0x27, 0x38,
	0xec, 0xf9, 0xc9, 0x3c, 0x6e, 0xd5, 0x68, 0xca, 0xd6, 0xf4, 0x24, 0x72, 0xe9, 0xf1, 0xee, 0x3c,
	0xf6, 0x8c, 0xc0, 0x99, 0xb5, 0x80, 0x1a, 0x5d, 0xd1, 0xca, 0xbf, 0x73, 0x00, 0x0b, 0x46, 0x90,
	0xac, 0xa7, 0x9c, 0xa0, 0x99, 0xa0, 0x59, 0x67, 0x32, 0x09, 0x0a, 0xf9, 0x76, 0x4e, 0x31, 0x4b,
	0x64, 0x26, 0x92, 0x53, 0x11, 0xe1, 0xc0, 0xdc, 0xc5, 0x19, 0x87, 0x72, 0x39, 0x7f, 0x6a, 0xe2,
	0xfb, 0x9e, 0x1a, 0x35, 0x7f, 0x31, 0xf5, 0x9d, 0x31, 0x8d, 0x79, 0x43, 0x67, 0x22, 0xba, 0x07,
	0xb5, 0xd8, 0x9b, 0xe1, 0x28, 0x76, 0x66, 0x01, 0x8d, 0xb7, 0xa0, 0x2f, 0x14, 0xf2, 0x8f, 0x1c,
	0x34, 0x17, 0x1e, 0xf4, 0xbd, 0xa5, 0x47, 0x75, 0x39, 0x9f, 0xf9, 0x65, 0x3e, 0xa3, 0x36, 0xd4,
	0x67, 0xce, 0xb9, 0xb1, 0xec, 0x42, 0x51, 0x85, 0xf6, 0x52, 0xdf, 0x71, 0x1c, 0xb5, 0xc4, 0xb6,
	0x70, 0xe9, 0x63, 0x62, 0x1b, 0xe4, 0x3f, 0x39, 0xd8, 0x59, 0xe8, 0xbb, 0xee, 0xd9, 0x95, 0x51,
	0x65, 0x58, 0xf9, 0x0d, 0x58, 0x85, 0x15, 0xac, 0xc5, 0x58, 0x8b, 0x2b, 0xb1, 0x5e, 0x0a, 0x54,
	0x69, 0x25, 0x50, 0xc5, 0xfc, 0x95, 0xd7, 0xf2, 0x47, 0x6b, 0xd8, 0x20, 0x3a, 0xcd, 0x68, 0x9a,
	0xcb, 0xf2, 0x3b, 0x16, 0xde, 0x03, 0x8d, 0x95, 0x1c, 0x19, 0xc4, 0x49, 0xe8, 0xcf, 0xa8, 0x2b,
	0xf5, 0x83, 0xe6, 0x22, 0x12, 0x56, 0x84, 0x43, 0x9d, 0xae, 0xa1, 0xfb, 0xc0, 0xc7, 0x3e, 0x75,
	0x6a, 0x7d, 0x07, 0x1f, 0xfb, 0xc5, 0x6c, 0x0b, 0xcb, 0xd9, 0x6e, 0x41, 0xc5, 0x8b, 0x8c, 0xd8,
	0x0f, 0x71, 0x56, 0x42, 0x99, 0x48, 0x56, 0x4e, 0xbc, 0xef, 0x4c, 0xc2, 0xa6, 0xec, 0x55, 0x66,
	0xa2, 0xfc, 0x4b, 0x0e, 0xd2, 0xbc, 0x0e, 0xc8, 0x07, 0x05, 0x90, 0xbb, 0x8b, 0x1d, 0x47, 0xa1,
	0x9f, 0x04, 0x1f, 0x00, 0xe5, 0xb7, 0xb0, 0x4b, 0xcc, 0x33, 0x52, 0x11, 0x66, 0x5c, 0x97, 0xa9,
	0x57, 0xbc, 0x34, 0xf9, 0x4b, 0xa8, 0xd2, 0x18, 0x24, 0xd3, 0xe9, 0x75, 0xed, 0xca, 0x3f, 0x73,
	0xb0, 0xa3, 0x1d, 0x68, 0x5a, 0x12, 0xbd, 0x1e, 0xe0, 0x6b, 0x27, 0x59, 0xf8, 0x28, 0x49, 0x7e,
	0x47, 0x31, 0x9a, 0xd7, 0xc4, 0xf8, 0xa0, 0x80, 0xf1, 0x23, 0xe4, 0x38, 0x48, 0x93, 0x40, 0x00,
	0x14, 0x7b, 0x1a, 0xc9, 0x42, 0xd6, 0xd3, 0xee, 0x03, 0x38, 0x41, 0xd0, 0x75, 0x5d, 0x5a, 0xbf,
	0xd3, 0x44, 0x14, 0x34, 0xd7, 0x6e, 0xc6, 0x5f, 0x41, 0x2d, 0x77, 0x68, 0xc3, 0x95, 0x85, 0x19,
	0x21, 0x2d, 0x33, 0x4c, 0x94, 0x9f, 0x42, 0xc5, 0xfa, 0x97, 0x47, 0x7f, 0xe0, 0xa0, 0x6a, 0xb1,
	0xbe, 0x21, 0x83, 0x98, 0x44, 0x38, 0xa4, 0xdd, 0xfb, 0x92, 0x4c, 0x90, 0x35, 0xf4, 0x69, 0x3e,
	0x74, 0xf1, 0x9d, 0xe6, 0xc1, 0x7f, 0xd3, 0x3d, 0xd6, 0x55, 0x7d, 0x40, 0x68, 0xf3, 0xc5, 0x7c,
	0x14, 0xcb, 0xa8, 0x98, 0xce, 0x45, 0x4c, 0x96, 0x63, 0x00, 0xab, 0xa7, 0x9c, 0xbb, 0xaf, 0x9d,
	0xf9, 0x29, 0x46, 0x0f, 0xa1, 0x3c, 0xc1, 0xea, 0x7c, 0xe2, 0x67, 0xd4, 0x68, 0xa4, 0x97, 0x3d,
	0xa7, 0x3a, 0x3d, 0x5b, 0x43, 0x8f, 0x56, 0x06, 0xa4, 0x26, 0x83, 0xb4, 0x32, 0x1e, 0x15, 0x0a,
	0xa7, 0x40, 0xaf, 0x65, 0xa2, 0xfc, 0x04, 0xca, 0x56, 0xef, 0x85, 0xef, 0xcd, 0xd1, 0x27, 0x50,
	0x3a, 0x25, 0x61, 0xcc, 0x22, 0xb0, 0xc3, 0x4c, 0xa5, 0x3c, 0x4b, 0xd7, 0x64, 0x9b, 0x80, 0x24,
	0xdb, 0xc9, 0x60, 0xba, 0xd5, 0x11, 0xc2, 0x06, 0x97, 0xcc, 0x9e, 0x04, 0x61, 0x49, 0xa7, 0xdf,
	0x04, 0x4f, 0x36, 0x6e, 0x64, 0xdd, 0x81, 0x89, 0x29, 0x9e, 0xe3, 0xc4, 0x8b, 0xaf, 0x81, 0x87,
	0x6c, 0xff, 0xa0, 0x78, 0x34, 0x6f, 0x7e, 0x5a, 0x34, 0x2e, 0x6c, 0xc4, 0xf3, 0x37, 0x07, 0x35,
	0xab, 0xc7, 0x2a, 0xf8, 0x56, 0x78, 0x0a, 0x6c, 0xe1, 0xd7, 0xd8, 0xb2, 0x71, 0x28, 0xd9, 0xfc,
	0xb2, 0x19, 0x91, 0x4b, 0x97, 0x97, 0x14, 0x4a, 0xe4, 0x2b, 0xe7, 0x91, 0x25, 0x96, 0x56, 0xd6,
	0x47, 0x28, 0x56, 0x37, 0xaa, 0xcb, 0x75, 0xe3, 0x2f, 0x0e, 0x76, 0xac, 0x5e, 0x56, 0xdb, 0x58,
	0x71, 0x7b, 0xef, 0x93, 0xca, 0x43, 0xc4, 0x6f, 0x8e, 0x6a, 0x0a, 0x88, 0xc6, 0x24, 0x6a, 0x09,
	0x6d, 0xa1, 0xd3, 0xd0, 0x73, 0xf9, 0x8a, 0x40, 0x5c, 0x3d, 0x4b, 0x14, 0x9d, 0x2c, 0x6f, 0x76,
	0xb2, 0xb2, 0xec, 0xe4, 0x5b, 0xea, 0x64, 0xe6, 0x20, 0x9d, 0xd4, 0xb6, 0xca, 0xf1, 0x67, 0x0b,
	0x7e, 0x2d, 0xd5, 0xf1, 0xdc, 0x54, 0x4e, 0xb8, 0xf7, 0x4f, 0x72, 0xb2, 0x46, 0x20, 0x14, 0x5b,
	0xf0, 0x56, 0x10, 0x8a, 0x64, 0x22, 0x3c, 0x2b, 0xf6, 0xdd, 0xcf, 0x09, 0x69, 0x0f, 0xbd, 0x68,
	0xe6, 0x45, 0xd1, 0x76, 0xef, 0xee, 0x29, 0x20, 0xf2, 0xee, 0x70, 0x78, 0x31, 0x9a, 0x93, 0xdf,
	0x25, 0x24, 0xa3, 0x5b, 0x1e, 0xfd, 0x06, 0x6e, 0xaf, 0x1f, 0xdd, 0xfe, 0xf9, 0xde, 0x83, 0x1a,
	0x21, 0x4e, 0x2f, 0xeb, 0x3d, 0xc4, 0x91, 0x85, 0x42, 0xfe, 0x95, 0x83, 0x72, 0x5a, 0x23, 0xd1,
	0x5d, 0xa8, 0x4d, 0xb0, 0x1d, 0x85, 0xae, 0xed, 0x05, 0xd9, 0xcc, 0x5a, 0x99, 0x60, 0x23, 0x74,
	0xd5, 0x00, 0xdd, 0x87, 0x7a, 0xb6, 0x16, 0xf8, 0x61, 0xda, 0xc2, 0x4a, 0x7a, 0x8d, 0xae, 0x6a,
	0x7e, 0x18, 0xa3, 0x36, 0x34, 0x26, 0xd8, 0x8e, 0x5f, 0x87, 0xd8, 0x19, 0xdb, 0x59, 0x27, 0x2b,
	0xe9, 0x30, 0xc1, 0x26, 0x55, 0xa9, 0x63, 0x74, 0x07, 0x2a, 0x13, 0x6c, 0x27, 0xae, 0x37, 0xce,
	0x7e, 0x79, 0x95, 0x27, 0xd8, 0x72, 0xbd, 0x31, 0xba, 0x45, 0x0a, 0xb7, 0x1d, 0x79, 0xe9, 0x6f,
	0x00, 0x51, 0x2f, 0x4d, 0xb0, 0xe1, 0x8d, 0xd1, 0xff, 0xa0, 0x4a, 0xd4, 0xf8, 0xcd, 0xdc, 0xa7,
	0x74, 0x13, 0x29, 0x18, 0x22, 0xee, 0x3d, 0x86, 0x5a, 0xfe, 0x53, 0x1c, 0x95, 0x81, 0x1f, 0xbd,
	0x94, 0xfe, 0x83, 0x10, 0x34, 0xd5, 0xa1, 0xa9, 0xe8, 0xc3, 0x6e, 0xdf, 0x56, 0x74, 0x7d, 0xa4,
	0x4b, 0xdc, 0xde, 0x6f, 0xd9, 0x58, 0x9e, 0xf7, 0x1b, 0xb4, 0x0b, 0x75, 0xed, 0x40, 0xb3, 0x07,
	0x8a, 0x61, 0x74, 0x8f, 0x14, 0x89, 0x4b, 0x15, 0x66, 0xae, 0xe0, 0x91, 0x04, 0x0d, 0x43, 0x39,
	0xb6, 0x94, 0x61, 0x4f, 0xb1, 0xbb, 0xbd, 0x97, 0x92, 0x80, 0x9a, 0x00, 0x5a, 0xb7, 0xf7, 0x52,
	0x31, 0xa9, 0x2c, 0xa2, 0x2a, 0x88, 0x9a, 0xd5, 0xef, 0x4b, 0x25, 0xd4, 0x80, 0x6a, 0x6f, 0x34,
	0xd0, 0x46, 0xd6, 0xf0, 0x50, 0x2a, 0x93, 0x7d, 0xba, 0x69, 0xd8, 0x86, 0x7a, 0x34, 0xec, 0xf6,
	0xa5, 0x0a, 0xda, 0x21, 0x24, 0xb1, 0xd3, 0xa3, 0x52, 0x15, 0xdd, 0x04, 0x89, 0x5c, 0xad, 0x59,
	0xc6, 0xd7, 0xf9, 0x75, 0xb5, 0x54, 0x6b, 0x2e, 0x6b, 0x61, 0xef, 0x0f, 0x0e, 0xea, 0x85, 0x36,
	0x49, 0xaf, 0x54, 0x87, 0x47, 0x12, 0x47, 0xbf, 0x46, 0xc3, 0x23, 0x89, 0x27, 0x5f, 0x2f, 0x46,
	0xea, 0x50, 0x12, 0xc8, 0x45, 0xe4, 0xcb, 0xd6, 0x15, 0x43, 0x4b, 0xf1, 0x1d, 0x5b, 0xaa, 0x29,
	0x95, 0xc8, 0x02, 0xf9, 0x4a, 0x17, 0xca, 0xa8, 0x0e, 0x15, 0x43, 0x39, 0xa6, 0x5e, 0x54, 0x88,
	0xc0, 0xee, 0xab, 0x12, 0xa7, 0x33, 0xc1, 0xee, 0xab, 0x86, 0x29, 0xd5, 0xc8, 0xf2, 0xa1, 0x6a,
	0x0c, 0x54, 0xc3, 0x90, 0x00, 0xdd, 0x06, 0x74, 0x6c, 0x29, 0xfa, 0x2b, 0x7b, 0x34, 0xec, 0xab,
	0x43, 0xc5, 0xb6, 0x0c, 0x45, 0x37, 0xa4, 0x3a, 0xfa, 0x3f, 0xdc, 0x59, 0xd7, 0xa7, 0xb7, 0x35,
	0x9e, 0xdd, 0x81, 0x5b, 0xae, 0x3f, 0xdb, 0x3f, 0xf7, 0x1c, 0x7f, 0xe6, 0xed, 0x2f, 0xfe, 0xfd,
	0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x30, 0x72, 0x92, 0xe3, 0x0a, 0x12, 0x00, 0x00,
}
