// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control_message.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	control_message.proto

It has these top-level messages:
	PushServiceConfigMsg
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Server&Client sync status and command with this message.
type PushServiceConfigMsg struct {
	FetchBucket      *bool  `protobuf:"varint,1,opt,name=fetchBucket" json:"fetchBucket,omitempty"`
	UseBucketV2      *bool  `protobuf:"varint,2,opt,name=useBucketV2" json:"useBucketV2,omitempty"`
	ClientVersion    *int32 `protobuf:"varint,3,opt,name=clientVersion" json:"clientVersion,omitempty"`
	CloudVersion     *int32 `protobuf:"varint,4,opt,name=cloudVersion" json:"cloudVersion,omitempty"`
	Dots             *int32 `protobuf:"varint,5,opt,name=dots" json:"dots,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushServiceConfigMsg) Reset()                    { *m = PushServiceConfigMsg{} }
func (m *PushServiceConfigMsg) String() string            { return proto.CompactTextString(m) }
func (*PushServiceConfigMsg) ProtoMessage()               {}
func (*PushServiceConfigMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushServiceConfigMsg) GetFetchBucket() bool {
	if m != nil && m.FetchBucket != nil {
		return *m.FetchBucket
	}
	return false
}

func (m *PushServiceConfigMsg) GetUseBucketV2() bool {
	if m != nil && m.UseBucketV2 != nil {
		return *m.UseBucketV2
	}
	return false
}

func (m *PushServiceConfigMsg) GetClientVersion() int32 {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return 0
}

func (m *PushServiceConfigMsg) GetCloudVersion() int32 {
	if m != nil && m.CloudVersion != nil {
		return *m.CloudVersion
	}
	return 0
}

func (m *PushServiceConfigMsg) GetDots() int32 {
	if m != nil && m.Dots != nil {
		return *m.Dots
	}
	return 0
}

func init() {
	proto.RegisterType((*PushServiceConfigMsg)(nil), "protocol.PushServiceConfigMsg")
}

func init() { proto.RegisterFile("control_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0x89, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x3b, 0x18, 0xb9, 0x44, 0x02, 0x4a, 0x8b,
	0x33, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x9d, 0xf3, 0xf3, 0xd2, 0x32, 0xd3, 0x7d, 0x8b,
	0xd3, 0x85, 0x14, 0xb8, 0xb8, 0xd3, 0x52, 0x4b, 0x92, 0x33, 0x9c, 0x4a, 0x93, 0xb3, 0x53, 0x4b,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0x90, 0x85, 0x40, 0x2a, 0x4a, 0x8b, 0x53, 0x21, 0x9c,
	0x30, 0x23, 0x09, 0x26, 0x88, 0x0a, 0x24, 0x21, 0x21, 0x15, 0x2e, 0xde, 0xe4, 0x9c, 0xcc, 0xd4,
	0xbc, 0x92, 0xb0, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20,
	0x54, 0x41, 0x21, 0x25, 0x2e, 0x9e, 0xe4, 0x9c, 0xfc, 0xd2, 0x14, 0x98, 0x22, 0x16, 0xb0, 0x22,
	0x14, 0x31, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xfc, 0x92, 0x62, 0x09, 0x56, 0xb0, 0x1c, 0x98, 0x0d,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x78, 0x28, 0x7d, 0xec, 0xdc, 0x00, 0x00, 0x00,
}
